use_frameworks!

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'zawsdk_vk_ios_Example' do
  pod 'zawsdk_vk_ios', :path => '../'

  target 'zawsdk_vk_ios_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
